bind('q', 'normal', quit)
bind('<Return>', 'normal', open_selected_message)
bind('i', 'normal', enter_insert_mode)
bind('o', 'normal', enter_room_filter_mode)
bind('O', 'normal', enter_room_filter_mode_unread)
bind('k', 'normal', select_prev_message)
bind('j', 'normal', select_next_message)
bind('<Esc>', 'normal', deselect_message)
bind('G', 'normal', deselect_message)
bind('r', 'normal', function(c) c:start_reply(); c:enter_insert_mode() end)
bind('n', 'normal', select_next_room)
bind('p', 'normal', select_prev_room)
bind('<C-c>', 'normal', clear_message)

bind('<C-c>', 'insert', clear_message)
bind('<Esc>', 'insert', enter_normal_mode)
bind('<Return>', 'insert', send_message)

bind('<C-n>', 'roomfilter', select_next_room)
bind('<C-p>', 'roomfilter', select_prev_room)
bind('<Esc>', 'roomfilter', enter_normal_mode)
bind('<Return>', 'roomfilter', accept_room_selection)

bind('<C-n>', 'roomfilterunread', select_next_room)
bind('<C-p>', 'roomfilterunread', select_prev_room)
bind('<Esc>', 'roomfilterunread', enter_normal_mode)
bind('<Return>', 'roomfilterunread', accept_room_selection)
